# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
 build:
   docker:
   - image: circleci/openjdk:11-jdk

   working_directory: ~/repo

   environment:
     JVM_OPTS: -Xmx3200m
     TERM: dumb
   steps:
   - checkout

   - restore_cache:
       keys:
       - v1-dependencies-{{ checksum "build.gradle"}}
       - v1-dependencies

   - run: gradle dependencies

#   - run: mvn dependency:go-offline

   - save-cache:
       paths:
       - ~/.gradle
       key: v1-dependencies-{{ checksum "build.gradle"}}
   - run: gradle-test